// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./interfaces/IZKVerifier.sol";

/**
 * @title StubZKVerifier
 * @notice A placeholder verifier used during development and testing.
 *         Always returns true — simulates a successful proof verification
 *         without requiring a real ZK proving system.
 *
 * @dev In production, swap this for a real Groth16 / PLONK verifier
 *      generated by your proving toolchain (snarkjs, circom, etc.)
 */
contract StubZKVerifier is IZKVerifier {
    /**
     * @notice Always approves any proof — this is intentional for the stub.
     * @dev The parameters are accepted to satisfy the interface but ignored.
     */
    function verifyProof(
        bytes memory,
        uint256[] memory
    ) external pure returns (bool) {
        return true;
    }
}
